### PR TITLE
Update grunt version

### PR DESCRIPTION
**Pull request by ErisDS**
Updated grunt to 0.4.2 (latest)

### CODE REVIEW

**Comment by jaubourg** [comment]
I haven't touched this in a long time (jQuery does not use it anymore). I'd be happy to merge this but could you replace the version with a sensible value? Keeping the RC definitely seems like a bad idea ;)

**Comment by ErisDS** [comment]
Updated to latest instead. 

[Ghost](http://github.com/TryGhost/Ghost) is using this as part of its build process. I'm interested in updating it to be a bit more configurable / multitask etc. Is that something you'd be willing to accept?

**Comment by jaubourg** [comment]
Definitely interested if it can help on your end.

**Comment by ErisDS** [comment]
Cool, then I will work on some more in depth changes. In the meantime, could you publish the latest update to npm?

Thanks!

**Comment by jaubourg** [comment]
Done.

**Pull request merged**
