### PR TITLE
Updating to Grunt 0.4

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by jaubourg** [comment]
Just arrived at Phuket. Don't wanna hold jQuery because I'm out of town ;) I made you a collaborator. Just ping me if there is any problem.

**Comment by jaubourg** [comment]
Silly me just realized I'll have to `npm publish` it anyway...

**Comment by mikesherov** [comment]
@jaubourg, can you publish?

**Comment by ctalkington** [comment]
also the bin file wont work anymore. as `npmTasks` was removed.

**Pull request merged**
